version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: futbol-league-app
    ports:
      - "8086:8000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
